config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'posts#main'
  devise_for :users, :controllers => {:sessions => "sessions"}
  resources :users do
    get :followers
    get :followed_people
    post "follow", to: "following_relationships#create"
    post "unfollow", to: "following_relationships#destroy"
    resources :achievements, only: [:index]
    post 'add_to_blacklist', to: 'blacklists#create'
    post 'remove_from_blacklist', to: 'blacklists#destroy'
    resources :bans, only: [:new, :create]
  end
  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy]
  get :main, to: 'posts#main'
  get :new, to: 'posts#latest', as: 'latest'
  get :hot, to: 'posts#hot'
  get :favourites, to: 'posts#favourites'
  get ':category_name', to: 'categories#show', as: :categories_show
  put ':category_name', to: 'categories#update', as: :categories_update
  delete ':category_name', to: 'categories#destroy', as: :categories_delete
  scope ':category_name', as: :categories_show do
    post 'add_to_favourites', to: 'favourite_categories#create'
    post 'remove_from_favourites', to: 'favourite_categories#destroy'
    resources :posts, only: [:show] do
      resources :comments
      resources :votes, only: [:create, :destroy]
    end
  end
  resources :comments do
    resources :votes
  end
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post, counter_cache: true
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :votes, as: :votable

  validates :body, presence: true

  scope :exclude_shadowbanned, -> { where.not(author: User.shadow_banned) }

  def to_s
    body
  end

  def calculate_votes
    positive = self.votes.where(value: 1).count
    negative = self.votes.where(value: -1).count
    positive - negative
  end
end

# == Schema Information
#
# Table name: comments
#
#  id              :integer          not null, primary key
#  body            :text             not null
#  post_id         :integer          not null
#  author_id       :integer          not null
#  created_at      :datetime
#  updated_at      :datetime
#  upvotes_count   :integer          default(0)
#  downvotes_count :integer          default(0)
#
# Indexes
#
#  index_comments_on_author_id  (author_id)
#  index_comments_on_post_id    (post_id)
#

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :deny_access, if: :spammer?
  expose(:post)
  expose(:comment, attributes: :comment_params)

  def create
    comment.author = current_user
    comment.post = post
    comment.save
    redirect_to categories_show_post_path(post.category, post)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def spammer?
    current_user.spammer?(post)
  end
end

app/views/comments/_comment.html.haml
.comment
  = link_to image_tag(comment.author.avatar.url(:thumb)) , user_path(comment.author)
  - if comment.author.gender == 'male'
    .user-color-panel-thumb.blue
  - elsif comment.author.gender == 'female'
    .user-color-panel-thumb.pink
  - else
    .user-color-panel-thumb.black
  .comment-author
    %span.author= link_to comment.author, user_path(comment.author)
    = "#{time_ago_in_words(comment.created_at)} ago"
    = link_to "DOWN #{comment.downvotes_count}", comment_votes_path(comment, value: -1), method: :post, class: 'pull-right vote'
    = link_to "UP #{comment.upvotes_count}", comment_votes_path(comment, value: 1), method: :post, class: 'pull-right vote'
  .comment-body
    = comment

app/views/comments/_form.html.haml
.col-xs-8
  = simple_form_for comment, url: categories_show_post_comments_path(post.category.name, post) do |form|
    = form.input :body, label: false

    = form.submit 'Save', class: 'btn btn-default'