config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'posts#main'
  devise_for :users, :controllers => {:sessions => "sessions"}
  resources :users do
    get :followers
    get :followed_people
    post "follow", to: "following_relationships#create"
    post "unfollow", to: "following_relationships#destroy"
    resources :achievements, only: [:index]
    post 'add_to_blacklist', to: 'blacklists#create'
    post 'remove_from_blacklist', to: 'blacklists#destroy'
    resources :bans, only: [:new, :create]
  end
  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy]
  get :main, to: 'posts#main'
  get :new, to: 'posts#latest', as: 'latest'
  get :hot, to: 'posts#hot'
  get :favourites, to: 'posts#favourites'
  get ':category_name', to: 'categories#show', as: :categories_show
  put ':category_name', to: 'categories#update', as: :categories_update
  delete ':category_name', to: 'categories#destroy', as: :categories_delete
  scope ':category_name', as: :categories_show do
    post 'add_to_favourites', to: 'favourite_categories#create'
    post 'remove_from_favourites', to: 'favourite_categories#destroy'
    resources :posts, only: [:show] do
      resources :comments
      resources :votes, only: [:create, :destroy]
    end
  end
  resources :comments do
    resources :votes
  end
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_messageable

  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :votes
  has_many :followed_relationships, class_name: FollowingRelationship, foreign_key: 'follower_id'
  has_many :followed_users, through: :followed_relationships
  has_many :follower_relationships, class_name: FollowingRelationship, foreign_key: 'followed_user_id'
  has_many :followers, through: :follower_relationships
  has_many :achievements
  has_many :blacklists
  has_many :blacklisted, through: :blacklists
  has_many :bans
  has_many :categories, foreign_key: 'owner_id'

  has_many :favourite_categories
  has_many :favourites, through: :favourite_categories, source: :category

  has_attached_file :avatar, styles: { medium: "150x150!", thumb: "40x40!" }, default_url: "default-:style.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  validates :nickname, presence: true,
                       length: { in: 3..20 },
                       uniqueness: true
  validates :gender, inclusion: { in: %w(undefined male female) },
                     allow_nil: true

  scope :shadow_banned, -> { joins(:bans).merge(Ban.where(type: 'shadowban')) }

  def to_s
    nickname
  end

  def spammer? post
    unless comments.where(post_id: post.id).last.nil?
      comments.where(post_id: post.id).last.created_at > 1.minutes.ago
    end
  end

  def followed_by? user
    followers.where(id: user.id).present?
  end

  def following? user
    followed_users.where(id: user.id).present?
  end

  def blacklisted? user
    blacklisted.where(id: user).present?
  end

  def banned? type='normal'
    bans.where('expiration > ? and type = ?', Time.now, type).present?
  end

  def has_achievement? achievement
    achievements.where(title: achievement).present?
  end

  def has_in_favourites? category
    favourites.where(id: category.id).present?
  end
end

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime
#  updated_at             :datetime
#  nickname               :string(255)      not null
#  avatar_file_name       :string(255)
#  avatar_content_type    :string(255)
#  avatar_file_size       :integer
#  avatar_updated_at      :datetime
#  gender                 :string(255)
#  admin                  :boolean          default(FALSE)
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

app/controllers/users_controller.rb
class UsersController < ApplicationController
  expose(:user)
end

app/views/users/show.html.haml
= image_tag user.avatar.url(:medium)
%h2.user-panel= user
- if user.gender == 'male'
  .user-color-panel.blue
- elsif user.gender == 'female'
  .user-color-panel.pink
- else
  .user-color-panel.black

- unless current_user == user

  = link_to 'Send message', new_conversation_path(target: user)
  %br

  - if current_user.following?(user)
    = link_to 'Unfollow', user_unfollow_path(user), method: :post
  - else
    = link_to 'Follow', user_follow_path(user), method: :post

  %br
  - if current_user.blacklisted?(user)
    = link_to 'Remove from blacklist', user_remove_from_blacklist_path(user), method: :post
  - else
    = link_to 'Add to blacklist', user_add_to_blacklist_path(user), method: :post

  %br
  = link_to 'Ban user', new_user_ban_path(user)
- else
  = link_to 'edit user', edit_user_registration_path
%br

%h4 Achievements
%ul
  - user.achievements.each do |achievement|
    %li= achievement.title


%h4= "#{user.followers.count} Followers"
%ul
  - user.followers.each do |follower|
    %li.following-rel-pics
      = link_to image_tag(follower.avatar.url(:thumb)) , user_path(follower)
      = link_to follower, user_path(follower)
      - if follower.gender == 'male'
        .user-color-panel-thumb.blue
      - elsif follower.gender == 'female'
        .user-color-panel-thumb.pink
      - else
        .user-color-panel-thumb.black

%h4= "#{user.followed_users.count} Following"
%ul
  - user.followed_users.each do |followed_user|
    %li.following-rel-pics
      = link_to image_tag(followed_user.avatar.url(:thumb)) , user_path(followed_user)
      = link_to followed_user, user_path(followed_user)
      - if followed_user.gender == 'male'
        .user-color-panel-thumb.blue
      - elsif followed_user.gender == 'female'
        .user-color-panel-thumb.pink
      - else
        .user-color-panel-thumb.black