config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'posts#main'
  devise_for :users, :controllers => {:sessions => "sessions"}
  resources :users do
    get :followers
    get :followed_people
    post "follow", to: "following_relationships#create"
    post "unfollow", to: "following_relationships#destroy"
    resources :achievements, only: [:index]
    post 'add_to_blacklist', to: 'blacklists#create'
    post 'remove_from_blacklist', to: 'blacklists#destroy'
    resources :bans, only: [:new, :create]
  end
  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy]
  get :main, to: 'posts#main'
  get :new, to: 'posts#latest', as: 'latest'
  get :hot, to: 'posts#hot'
  get :favourites, to: 'posts#favourites'
  get ':category_name', to: 'categories#show', as: :categories_show
  put ':category_name', to: 'categories#update', as: :categories_update
  delete ':category_name', to: 'categories#destroy', as: :categories_delete
  scope ':category_name', as: :categories_show do
    post 'add_to_favourites', to: 'favourite_categories#create'
    post 'remove_from_favourites', to: 'favourite_categories#destroy'
    resources :posts, only: [:show] do
      resources :comments
      resources :votes, only: [:create, :destroy]
    end
  end
  resources :comments do
    resources :votes
  end
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :category
  has_many :comments
  has_many :votes, as: :votable

  validates :title, presence: true
  validates :link, presence: true,
                   uniqueness: true,
                   url: true

  scope :main,                            -> { where('votes_differential > 1') }
  scope :hot,                             -> { where('votes_differential > 10') }
  scope :latest,                          -> { where('created_at > ?', 24.hours.ago) }
  scope :current_month,                   -> { where('EXTRACT(MONTH from posts.created_at) > ?', Time.now.month-1) }
  scope :exclude_blacklisted,       ->(user) { where.not(author_id: user.blacklisted) }
  scope :from_favourite_categories, ->(user) { where(category_id: user.favourites) }

  def editable? user
    author == user && comments.count == 0 && created_at > 1.minutes.ago
  end
  
  def calculate_votes
    positive = self.votes.where(value: 1).count
    negative = self.votes.where(value: -1).count
    positive - negative
  end
end

# == Schema Information
#
# Table name: posts
#
#  id                 :integer          not null, primary key
#  title              :text             not null
#  link               :string(255)      not null
#  author_id          :integer          not null
#  created_at         :datetime
#  updated_at         :datetime
#  votes_differential :integer          default(0), not null
#  category_id        :integer          not null
#  comments_count     :integer          default(0)
#
# Indexes
#
#  index_posts_on_author_id  (author_id)
#

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :html

  before_action :authenticate_user!, except: [:index, :show, :hot, :latest, :main]
  before_action :deny_access, unless: :editable?, only: [:edit, :update, :destroy]
  expose(:post, attributes: :post_params)
  expose(:posts) { Post.order('created_at DESC').page params[:page] }
  expose(:comment) { Comment.new }

  def create
    post.author = current_user
    if post.save
      redirect_to categories_show_post_path(post.category.name, post)
    else
      render :new
    end
  end

  def update
    if post.save
      redirect_to categories_show_post_path(post.category.name, post)
    else
      render :edit
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :link, :category_id)
  end

  def editable?
    post.editable?(current_user)
  end
end

app/views/posts/_form.html.haml
.col-xs-10
  = simple_form_for post do |form|
    = form.input :title
    = form.input :link
    = form.input :category_id,  collection: Category.all
    
    = form.submit class: 'btn btn-primary'

app/views/posts/_posts.html.haml
%table.table.table-striped.table-hover
  %tbody
    - posts.each do |post|
      %tr
        %td.votes
          = button_to categories_show_post_votes_path(post.category.name, post, value: 1), class: 'btn btn-default btn-xs' do
            %span.glyphicon.glyphicon-chevron-up
          = button_to categories_show_post_votes_path(post.category.name, post, value: -1), class: 'btn btn-default btn-xs' do
            %span.glyphicon.glyphicon-chevron-down
        %td.votes-count
          = post.votes_differential
        %td
          = link_to post.title, post.link, class: 'post-title'
          = "(#{URI.parse(post.link).host})"
          .post-author
            = "submitted #{time_ago_in_words(post.created_at)} ago by "
            = link_to post.author, user_path(post.author)
            = ' to '
            = link_to post.category, categories_show_path(post.category.name)
          .comments-count
            = link_to "#{pluralize(post.comments_count, 'comment')}", categories_show_post_path(post.category.name, post)

app/views/posts/edit.html.haml
= render 'form'

app/views/posts/favourites.html.haml
- if current_user
  = render "posts", posts: Post.where(id: Post.from_favourite_categories(current_user))
- else
  = render 'posts', posts: posts.latest
= paginate posts

app/views/posts/hot.html.haml
- if current_user
  = render "posts", posts: posts.exclude_blacklisted(current_user) & posts.hot
- else
  = render 'posts', posts: posts.hot
= paginate posts

app/views/posts/index.html.haml
- if current_user
  = render "posts", posts: posts.exclude_blacklisted(current_user) & posts
- else
  = render 'posts'
= paginate posts

app/views/posts/latest.html.haml
- if current_user
  = render "posts", posts: posts.exclude_blacklisted(current_user) & posts.latest
- else
  = render 'posts', posts: posts.latest
= paginate posts

app/views/posts/main.html.haml
- if current_user
  = render "posts", posts: posts.exclude_blacklisted(current_user) & posts.main
- else
  = render 'posts', posts: posts.main
= paginate posts

app/views/posts/new.html.haml
= render 'form'

app/views/posts/show.html.haml
%table
  %tbody
    %td.votes
      = button_to categories_show_post_votes_path(post.category, post, value: 1), class: 'btn btn-default btn-xs' do
        %span.glyphicon.glyphicon-chevron-up
      = button_to categories_show_post_votes_path(post.category, post, value: -1), class: 'btn btn-default btn-xs' do
        %span.glyphicon.glyphicon-chevron-down
    %td.votes-count
      = post.calculate_votes
    %td
      %h3.post-title
        = link_to post.title, post.link

.post-author.main
  = "submitted #{time_ago_in_words(post.created_at)} ago by "
  %span.author= link_to post.author, user_path(post.author)

  - if post.author == current_user && post.editable?(current_user)
    = link_to 'Edit', edit_post_path(post), class: 'btn btn-default btn-xs'
  - elsif post.author == current_user
    = link_to 'Edit', edit_post_path(post), class: 'btn btn-default btn-xs', disabled: 'disabled'

%h5.comments
  = "#{pluralize(post.comments.count, 'comment')}"

= render 'comments/form'

.col-xs-8
  .comments
    - if current_user && current_user.banned?('shadowban')
      = render (post.comments.exclude_shadowbanned + post.comments.where(author: current_user)).sort_by(&:created_at).reverse
    - else
      = render post.comments.exclude_shadowbanned