config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'posts#main'
  devise_for :users, :controllers => {:sessions => "sessions"}
  resources :users do
    get :followers
    get :followed_people
    post "follow", to: "following_relationships#create"
    post "unfollow", to: "following_relationships#destroy"
    resources :achievements, only: [:index]
    post 'add_to_blacklist', to: 'blacklists#create'
    post 'remove_from_blacklist', to: 'blacklists#destroy'
    resources :bans, only: [:new, :create]
  end
  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy]
  get :main, to: 'posts#main'
  get :new, to: 'posts#latest', as: 'latest'
  get :hot, to: 'posts#hot'
  get :favourites, to: 'posts#favourites'
  get ':category_name', to: 'categories#show', as: :categories_show
  put ':category_name', to: 'categories#update', as: :categories_update
  delete ':category_name', to: 'categories#destroy', as: :categories_delete
  scope ':category_name', as: :categories_show do
    post 'add_to_favourites', to: 'favourite_categories#create'
    post 'remove_from_favourites', to: 'favourite_categories#destroy'
    resources :posts, only: [:show] do
      resources :comments
      resources :votes, only: [:create, :destroy]
    end
  end
  resources :comments do
    resources :votes
  end
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %a.navbar-brand{href: "../"} reddit
      %button.navbar-toggle{"data-target" => "#navbar-main", "data-toggle" => "collapse", type: "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    #navbar-main.navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li{class: (current_page?(main_path) || current_page?(root_path)) && 'active'}
          = link_to 'main', main_path
        %li{class: current_page?(latest_path) && 'active'}
          = link_to 'new', latest_path
        %li{class: current_page?(hot_path) && 'active'}
          = link_to 'hot', hot_path
        %li{class: current_page?(posts_path) && 'active'}
          = link_to 'all', posts_path
        - if current_user
          %li{class: current_page?(favourites_path) && 'active'}
            = link_to 'favourites', favourites_path
          
      %ul.nav.navbar-nav.navbar-right
        -if user_signed_in?
          %li
            = link_to "Messages (#{current_user.mailbox.inbox(:unread => true).count} unread)", conversations_path
          %li
            = link_to current_user, user_path(current_user)
          %li
            = link_to 'Log out', destroy_user_session_path, method: :delete
        - else
          %li
            = link_to 'Sign in', new_user_session_path
          %li
            = link_to 'Sign up',  new_user_registration_path

app/views/layouts/_right.html.haml
= link_to 'Submit a new link', new_post_path, class: 'btn btn-default btn-lg'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title reddit
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      %div
        - if flash.notice
          .alert.alert-success{role: "alert"} 
            = flash.notice 
        - if flash.alert
          .alert.alert-danger{role: "alert"}
            = flash.alert

      .col-md-10
        = yield
      .col-md-2
        = render 'layouts/right'
        = yield :right